# Generated by Django 5.0.7 on 2024-07-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_deployment_chatbot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='config_file_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deployment',
            name='chatbot_name',
            field=models.CharField(max_length=255),
        ),
    ]
