# Generated by Django 5.0.7 on 2024-07-31 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_deployment_config_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='config_file',
        ),
    ]
