# Generated by Django 5.0.7 on 2024-07-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_deployment_config_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_name',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
