# Generated by Django 5.0.7 on 2024-08-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='resource_name',
            field=models.CharField(blank=True, editable=False, max_length=511),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
