# Generated by Django 5.0.7 on 2024-08-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_deployment_resource_name_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('marked_for_deletion', 'Marked for Deletion')], default='active', max_length=20),
        ),
    ]
