# Generated by Django 5.0.7 on 2024-08-02 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_deployment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='config_file_name',
            new_name='config_file_path',
        ),
    ]
