# Generated by Django 5.0.7 on 2024-08-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_config_file_name_deployment_config_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='config_file_name',
            field=models.CharField(default='eggnog', max_length=255),
            preserve_default=False,
        ),
    ]
