# Generated by Django 5.0.7 on 2024-08-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_deployment_config_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='has_deployment',
            field=models.BooleanField(default=False),
        ),
    ]
