# Generated by Django 5.0.7 on 2024-08-03 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_uploadedfile_has_deployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='config_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='accounts.uploadedfile'),
        ),
    ]
