# Generated by Django 5.0.7 on 2024-08-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_deployment_config_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='chat_configuration_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
