# Generated by Django 5.0.7 on 2024-12-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_uploadedfile_chat_configuration_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='chat_configuration_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='uploadedfile',
            unique_together={('user', 'chat_configuration_name')},
        ),
    ]
