services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/backend/staticfiles  # Shared volume for static files
    env_file:
      - .env.prod
    depends_on:
      - rabbitmq
      - celery

  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/usr/share/nginx/html/static  # Mount the same volume for static files
      - ./nginx.conf:/etc/nginx/nginx.conf          # Nginx configuration
    ports:
      - "80:80"  # Expose port 80 for HTTP traffic
    depends_on:
      - web

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"   # RabbitMQ service port
      - "15672:15672" # RabbitMQ management port
    env_file:
      - .env.prod

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery  # Use a separate Dockerfile for Celery
    env_file:
      - .env.prod
    depends_on:
      - rabbitmq

volumes:
  static_volume: