version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/scripts/start.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - rabbitmq
      - celery

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env.prod
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: demodemodemo

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    env_file:
      - .env.prod
    depends_on:
      - rabbitmq